//import { findPlanPercentages } from "../../../App/CardCheckoutNew/utils/findPlanPercentages";
// @ts-ignore
import { findPlanPercentages } from "../../../components/utils/splitRule";
export const allCards = ["mastercard", "visa", "americanexpress", "hipercard", "elo"];
export const allInstallments = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "0"];
export const allInsurances = [true, false];

export const sellerZoopPlanCompleteStandard = {
    activePlan: "standard",
    standard: {
        zoopFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
        ziroMarkupFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
        ziroAntifraudFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
    },
    financedD30: {
        zoopFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
        ziroMarkupFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
        ziroAntifraudFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
    },
};
export const sellerZoopPlanCompleteFinancedD30 = {
    activePlan: "financedD30",
    standard: {
        zoopFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
        ziroMarkupFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
        ziroAntifraudFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
    },
    financedD30: {
        zoopFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
        ziroMarkupFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
        ziroAntifraudFee: {
            americanexpress: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            elo: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            hipercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            mastercard: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
            visa: {
                installment1: 1,
                installment2: 2,
                installment3: 3,
                installment4: 4,
                installment5: 5,
                installment6: 6,
                installment7: 7,
                installment8: 8,
                installment9: 9,
                installment10: 10,
                installment11: 11,
                installment12: 12,
                installment0: 1.5,
            },
        },
    },
};

export const allSellerZoopPlanComplete = [sellerZoopPlanCompleteStandard, sellerZoopPlanCompleteFinancedD30];
allCards.map((cardBrand) => {
    allInstallments.map((installments) => {
        allInsurances.map((insurance) => {
            allSellerZoopPlanComplete.map((sellerZoopPlan) => {
                const activePlan = sellerZoopPlan.activePlan;
                describe("Testing all possibilities", () => {
                    test("test", () => {
                        expect(findPlanPercentages({ cardBrand, installments, insurance, sellerZoopPlan })).toEqual({
                            percentageZiroMarkup: sellerZoopPlan[activePlan]["ziroMarkupFee"][cardBrand][`installment${installments}`],
                            percentageZiroAntifraud: insurance
                                ? sellerZoopPlan[activePlan]["ziroAntifraudFee"][cardBrand][`installment${installments}`]
                                : "N/A",
                        });
                    });
                });
            });
        });
    });
});
