import {
  grayColor1,
  fontTitle,
  fontSizeInput,
  gradient,
  shadow,
} from '@ziro/theme';

export const container = {
    display: 'grid',
    gridGap: '20px',
    alignContent: 'start',
    minHeight: '100vh',
    maxWidth:
      window.innerWidth > 500 ? '385px' : window.innerWidth - 15,
    margin: '0 auto',
  },
  card = {
    borderRadius: '3px',
    textAlign: 'center',
    boxShadow: 'rgba(34, 34, 34, 0.3) 0px 0px 12px -3px',
    background: 'white',
  },
  image = {
    objectFit: 'contain',
    width: '100%',
    borderTopLeftRadius: '3px',
    borderTopRightRadius: '3px'
  },
  brand = {},
  cartQty = {
    fontSize: '1.2rem',
    color: grayColor1
  },
  timestampStyle = {
    color: grayColor1,
    fontSize: '1.2rem',
    justifySelf: 'end',
  },
  cardBottom = {
    display: 'grid',
    alignItems: 'center',
    gridRowGap: '10px',
    padding: '10px 10px 20px',
  },
  icons = (showPrice) => ({
    display: 'grid',
    gridTemplateColumns: 'auto auto 1fr auto',
    gridGap: '10px',
    alignItems: 'end',
    justifyItems: 'start',
  }),
  values = {
    fontFamily: fontTitle,
    fontSize: '1.5rem',
  },
  priceButton = {
    justifySelf: 'end',
    display: 'grid',
    WebkitAppearance: 'none',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    MozAppearance: 'none',
    outline: 'none',
    cursor: 'pointer',
    width: '60px',
    maxWidth: '100px',
    padding: '6px 0px',
    border: 'none',
    borderRadius: '20px',
    fontFamily: fontTitle,
    fontSize: '1.1rem',
    color: '#FFF',
    textAlign: 'center',
    background: gradient,
    boxShadow: `0px 3px 8px -3px rgba(34,34,34,0.65)`,
  },
  info = {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    alignItems: 'center',
    justifyItems: 'start',
  },
  cart = {
    margin: '0px',
    padding: '10px 0px 10px',
  },
  likes = { textAlign: 'left' },
  toastStyle = {
    position: 'fixed',
    marginTop: '15px',
    zIndex: '9999',
    maxWidth: '500px',
    display: 'block',
    WebkitAppearance: 'none',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    MozAppearance: 'none',
    outline: 'none',
    cursor: 'pointer',
    width: '100%',
    padding: '10px 0px',
    border: 'none',
    borderRadius: '5px',
    fontFamily: fontTitle,
    color: '#FFF',
    textAlign: 'center',
    background: gradient,
    boxShadow: `${shadow}`,
  };
