import {
  grayColor1,
  fontTitle,
  fontSizeInput,
  gradient,
  shadow,
  alertColor,
  fontSizeSmall,
  primaryColor,
  fontSizeNormal,
} from '@ziro/theme';

export const container = {
    display: 'grid',
    gridGap: '20px',
    alignContent: 'start',
    minHeight: '100vh',
    maxWidth:
      window.innerWidth > 500 ? '385px' : window.innerWidth - 15,
    margin: '0 auto',
  },
  card = {
    borderRadius: '3px',
    textAlign: 'center',
    boxShadow: 'rgba(34, 34, 34, 0.3) 0px 0px 12px -3px',
    background: 'white',
  },
  overlayContainer = {
    position: 'relative',
  },
  overlay = {
    position: 'absolute',
    bottom: '0',
    display: 'grid',
    alignItems: 'center',
    width: '100%',
    height: window.innerWidth < 500 ? '12%' : '10%',
    fontFamily: fontTitle,
    fontSize: window.innerWidth < 500 ? '1.5rem' : '1.8rem',
    fontWeight: '600',
    color: 'white',
    textAlign: 'center',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    background: alertColor, //'rgba(34,34,34,0.9)',
    boxShadow: 'rgba(34, 34, 34, 0.3) 0px -5px 15px -1px',
  },
  image = {
    objectFit: 'contain',
    width: '100%',
    borderTopLeftRadius: '3px',
    borderTopRightRadius: '3px',
  },
  cartQty = {
    fontSize: '1.2rem',
    color: grayColor1,
  },
  timestampStyle = {
    color: grayColor1,
    fontSize: '1.2rem',
    justifySelf: 'end',
  },
  cardBottom = {
    display: 'grid',
    alignItems: 'center',
    gridRowGap: '10px',
    padding: '10px 10px 20px',
  },
  icons = (showPrice) => ({
    display: 'grid',
    gridTemplateColumns: 'auto auto 1fr auto',
    gridGap: '15px',
    alignItems: 'end',
    justifyItems: 'start',
  }),
  values = {
    justifySelf: 'end',
    display: 'grid',
    fontFamily: fontTitle,
    fontSize: '1.5rem',
  },
  priceButton = {
    justifySelf: 'end',
    display: 'grid',
    WebkitAppearance: 'none',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    MozAppearance: 'none',
    outline: 'none',
    cursor: 'pointer',
    width: '60px',
    maxWidth: '100px',
    padding: '6px 0px',
    border: 'none',
    borderRadius: '20px',
    fontFamily: fontTitle,
    fontSize: '1.1rem',
    color: '#FFF',
    textAlign: 'center',
    background: gradient,
    boxShadow: `0px 3px 8px -3px rgba(34,34,34,0.65)`,
  },
  info = {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    alignItems: 'center',
    justifyItems: 'start',
  },
  cart = {
    margin: '0px',
    padding: '10px 0px 10px',
  },
  likes = { textAlign: 'left' },
  toastStyle = {
    position: 'fixed',
    marginTop: '15px',
    zIndex: '9999',
    maxWidth: '500px',
    display: 'block',
    WebkitAppearance: 'none',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    MozAppearance: 'none',
    outline: 'none',
    cursor: 'pointer',
    width: '100%',
    padding: '10px 0px',
    border: 'none',
    borderRadius: '5px',
    fontFamily: fontTitle,
    color: '#FFF',
    textAlign: 'center',
    background: gradient,
    boxShadow: `${shadow}`,
  },
  container2 = {
    display: 'grid',
    gridGap: '20px',
    alignContent: 'start',
    minHeight: '100vh',
    maxWidth:
      window.innerWidth > 500 ? '385px' : window.innerWidth - 15,
    margin: '0 auto',
  },
  card2 = {
    borderRadius: '3px',
    textAlign: 'center',
    boxShadow: 'rgba(34, 34, 34, 0.3) 0px 0px 12px -3px',
    background: 'white',
  },
  overlayContainer2 = {
    position: 'relative',
  },
  overlay2 = {
    position: 'absolute',
    bottom: '0',
    display: 'grid',
    alignItems: 'center',
    width: '100%',
    height: window.innerWidth < 500 ? '12%' : '10%',
    fontFamily: fontTitle,
    fontSize: window.innerWidth < 500 ? '1.5rem' : '1.8rem',
    fontWeight: '600',
    color: 'white',
    textAlign: 'center',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    background: alertColor, //'rgba(34,34,34,0.9)',
    boxShadow: 'rgba(34, 34, 34, 0.3) 0px -5px 15px -1px',
  },
  image2 = {
    objectFit: 'contain',
    width: '100%',
    borderTopLeftRadius: '3px',
    borderTopRightRadius: '3px',
  },
  cartQty2 = {
    fontSize: '1.2rem',
    color: grayColor1,
  },
  timestampStyle2 = {
    color: grayColor1,
    fontSize: '1.2rem',
    justifySelf: 'end',
  },
  cardBottom2 = {
    display: 'grid',
    alignItems: 'center',
    gridRowGap: '10px',
    padding: '10px 10px 20px',
  },
  icons2 = (showPrice) => ({
    display: 'grid',
    gridTemplateColumns: 'auto auto auto',
    gridGap: '15px',
    alignItems: 'end',
    justifyItems: 'start',
  }),
  values2 = {
    fontFamily: fontTitle,
    fontSize: '1.5rem',
  },
  registerButton = {
    justifySelf: 'start',
    display: 'grid',
    WebkitAppearance: 'none',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    MozAppearance: 'none',
    outline: 'none',
    cursor: 'pointer',
    width: '100px',
    maxWidth: '100px',
    padding: '6px 0px',
    border: 'none',
    borderRadius: '20px',
    fontFamily: fontTitle,
    fontSize: '1.1rem',
    color: '#FFF',
    textAlign: 'center',
    background: gradient,
    boxShadow: `0px 3px 8px -3px rgba(34,34,34,0.65)`,
    float: 'left',
  },
  howToBuy = {
    justifySelf: 'end',
    display: 'grid',
    fontFamily: fontTitle,
    fontSize: fontSizeSmall,
    color: primaryColor,
    textDecoration: 'underline',
  },
  priceButton2 = {
    justifySelf: 'end',
    display: 'grid',
    WebkitAppearance: 'none',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    MozAppearance: 'none',
    outline: 'none',
    cursor: 'pointer',
    width: '100%',
    maxWidth: '100px',
    padding: '6px 0px',
    border: 'none',
    borderRadius: '20px',
    fontFamily: fontTitle,
    fontSize: '1.1rem',
    color: '#FFF',
    textAlign: 'center',
    background: gradient,
    boxShadow: `0px 3px 8px -3px rgba(34,34,34,0.65)`,
  },
  info2 = {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    alignItems: 'center',
    justifyItems: 'start',
  },
  info3 = {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    alignItems: 'center',
    justifyItems: 'start',
  },
  info4 = {
    //display: 'grid',
    //gridTemplateColumns: '1fr',
    alignItems: 'center',
    justifyItems: 'start',
    fontSize: '1.2rem',
  },
  cart2 = {
    margin: '0px',
    padding: '10px 0px 10px',
  },
  likes2 = { textAlign: 'left' },
  toastStyle2 = {
    position: 'fixed',
    marginTop: '15px',
    zIndex: '9999',
    maxWidth: '500px',
    display: 'block',
    WebkitAppearance: 'none',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    MozAppearance: 'none',
    outline: 'none',
    cursor: 'pointer',
    width: '100%',
    padding: '10px 0px',
    border: 'none',
    borderRadius: '5px',
    fontFamily: fontTitle,
    color: '#FFF',
    textAlign: 'center',
    background: gradient,
    boxShadow: `${shadow}`,
  };
